#!/bin/bash

if [ "$1" == "" ]; then
    echo "Instruções:"
    echo
    echo -e "\033[1;32m  $0 server \033[0m       - Rodar Servidor (Venom)"
    echo -e "\033[1;32m  $0 clear \033[0m         - Limpa os tokens"
    echo
    exit 0
fi

cd $(dirname $0)

if [ "$1" == "server" ] || [ "$1" == "server/" ];then
    cd server/src
    node main.js
fi

if [ "$1" == "clear" ] || [ "$1" == "clear/" ];then
    cd server/src
    rm -rf ./tokens/*
    echo -e "Tokens apagados!"
fi
